polls_backend/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('polls.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

polls_backend/polls/urls.py
from django.urls import path

from .views import (AboutAuthorView, IndexView, QuestionView, ResultsView,
                    UsersListView, poll_detail, profile, vote)

app_name = 'polls'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('users', UsersListView.as_view(), name='users'),
    path('profile/<str:username>/', profile, name='profile'),
    path('<int:poll_id>/', poll_detail, name='poll_detail'),
    path('<int:pk>/questions', QuestionView.as_view(), name='questions'),
    path('<int:pk>/results/', ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', vote, name='vote'),
    path('author/', AboutAuthorView.as_view(), name='author'),
]

polls_backend/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name="users/logged_out.html"),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

polls_backend/polls/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import UniqueConstraint

User = get_user_model()


class Poll(models.Model):
    title = models.CharField('Название опроса', max_length=256, unique=True)
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'

    def __str__(self):
        return self.title


class Question(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    text = models.CharField('Текст вопроса', max_length=4000)

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'
        constraints = (
            UniqueConstraint(
                fields=('poll', 'text', ),
                name='unique_question',
            ),
        )

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField('Вариант ответа', max_length=500)
    votes = models.PositiveIntegerField('Голосов', default=0)

    class Meta:
        verbose_name = 'Вариант ответа'
        verbose_name_plural = 'Варианты ответов'
        constraints = (
            UniqueConstraint(
                fields=('question', 'choice', ),
                name='unique_choice',
            ),
        )

    def __str__(self):
        return self.choice


class Point(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        verbose_name='Пользователь',
        related_name='respondent',
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.DO_NOTHING,
        related_name='answered',
    )

    class Meta:
        verbose_name_plural = 'Баллы пользователей'
        constraints = (
            UniqueConstraint(
                fields=('question', 'user',),
                name='unique_point',
            ),
        )

polls_backend/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

polls_backend/polls/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic.base import TemplateView

from .models import Choice, Point, Poll, Question

User = get_user_model()


class IndexView(generic.ListView):
    '''Представление главной страницы'''

    template_name = 'polls/index.html'
    context_object_name = 'polls_list'

    def get_queryset(self):
        return Poll.objects.all()


def poll_detail(request, poll_id):
    '''Представление выбранного опроса'''

    context = {
        'poll': Poll.objects.get(id=poll_id),
        'questions': Question.objects.filter(poll_id=poll_id).order_by('id'),
    }
    return render(request, 'polls/poll.html', context)


class QuestionView(generic.DetailView):
    '''Представление вопросов'''

    model = Question
    template_name = 'polls/detail.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def vote(request, question_id):
    '''Представление голосования в опросах'''

    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Выберете вариант ответа!',
        })
    if Point.objects.filter(user=request.user, question=question).exists():
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Вы уже голосовали!',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        Point.objects.create(user=request.user, question=question)
        return HttpResponseRedirect(
            reverse('polls:results', args=(question.id,))
        )


class ResultsView(generic.DetailView):
    '''Представление результатов ответа'''

    model = Question
    template_name = 'polls/results.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class UsersListView(generic.ListView):
    '''Представление списка пользователей'''

    template_name = 'polls/users.html'
    context_object_name = 'point_list'

    def get_queryset(self):
        return User.objects.all()


def profile(request, username):
    '''Представление личной страницы пользователя'''

    user = get_object_or_404(User, username=username)
    questions = Point.objects.filter(user=user)

    context = {
        'user': user,
        'questions': questions,
    }
    return render(request, 'polls/profile.html', context)


class AboutAuthorView(TemplateView):
    '''Представление страницы об авторе'''
    template_name = 'about/author.html'

polls_backend/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('polls:index')
    template_name = 'users/signup.html'

polls_backend/templates/about/author.html
{% extends "base.html" %}

{% block title %}Об авторе проекта{% endblock %}

{% block content %}

<h1 align="center">Привет, меня зовут Вадим Шпак.</h1>
<h3 align="center">Был бы очень рад работать в "KOKOC Group"! &#129381;</h3>


<h5 align="center">Для связи: <a href="https://t.me/starboy_shpak/" target="_blank">написать в Telegram</a></span></h5>
</p>

{% endblock %} 

polls_backend/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Заголовок забыли{% endblock %}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
      <main>
          <div class="container py-5">
            {% block content %} Контент не подвезли :( {% endblock %}
          </div>
        </main>
    {% include 'includes/footer.html' %} 
  </body>
</html>

polls_backend/templates/includes/checking_form_errors.html
{% if form.errors %}
{% for field in form %}
  {% for error in field.errors %}            
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}

polls_backend/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <role="contentinfo">
    <p>© 2023 Copyright <span style="color:blue">Я</span>-опросник</p>
</footer>

polls_backend/templates/includes/form_card.html
{% load user_filters %}

{% for field in form %}
  <div class="form-group row my-3 p-3">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
    </label>
    <div>
      {{ field|addclass:'form-control' }}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
      {{ field.help_text|safe }}</small>  
    </div>
  </div>  
{% endfor %}

polls_backend/templates/includes/header.html
{% load static %}

<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'polls:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:blue">Я</span>-опросник
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'polls:author' %}active{% endif %}"
          href="{% url 'polls:author' %}">Об авторе</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'polls:users' %}active{% endif %}"
          href="{% url 'polls:users' %}">Рейтинг пользователей</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
          href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
          href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>      
</header>

polls_backend/templates/polls/detail.html
{% extends 'base.html' %}

{% block title %}{{ question.text|truncatechars:15 }}{% endblock %}

{% block content %}

        <h1>{{ question.text }}</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice }}</label><br>
            {% endfor %}

            <input type="submit" value="Проголосовать">
        </form>
{% endblock %}

polls_backend/templates/polls/index.html
{% extends 'base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <h1>Все опросы на сайте</h1>

    {% if polls_list %}
        <ul>
            {% for poll in polls_list %}
                <li><a href="{% url 'polls:poll_detail' poll.id %}">{{ poll.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет доступных опросов</p>
    {% endif %}
{% endblock %}

polls_backend/templates/polls/poll.html
{% extends 'base.html' %}

{% block title %}Опрос {{ poll.title|truncatechars:15 }}{% endblock %}

{% block content %}
    {% if poll %}
    <h5>Дата публикации опроса: {{ poll.pub_date|date:'d E Y'}}</h5>
        <ul>
            <h5>{{ poll.title }}</h5>
            {% for question in questions %}
                <li><a href="{% url 'polls:questions' question.id %}">{{ question.text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет доступных вопросов</p>
    {% endif %}
{% endblock %}

polls_backend/templates/polls/profile.html
{% extends 'base.html' %}

{% block title %}Профиль пользователя {{ user.username }}{% endblock %}

{% block content %}
  <div class="mb-5">
    <h1>Результаты пользователя {{ user.username }}</h1>
    <h3>Всего заработанно баллов: {{ questions.count }} </h3>
    <h3>Уровень пользователя:</h3>
    {% if questions.count < 3 %}
      <h3>"Новичок" &#127891;</h3>
    {% elif questions.count < 6 %}
      <h3>"Чемпион" &#127942;</h3>
    {% else %}
      <h3>"Легенда" &#127775;</h3>
    {% endif %}
  </div>


{% endblock %}

polls_backend/templates/polls/results.html
{% extends 'base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <h3>Спасибо, ваш голос учтен!</h3>
    <h3>Результаты голосования:</h3>
    <h5>{{ question.text }}</h5>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice }} -- {{ choice.votes }} проголосовавших</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:poll_detail' question.poll.id %}">Вернуться к опросу</a>
{% endblock %}

polls_backend/templates/polls/users.html
{% extends 'base.html' %}

{% block title %}Пользователи{% endblock %}

{% block content %}
    <h1>Список активных пользователей</h1>

    {% if point_list %}
        <ul>
            {% for user in point_list %}
            <li><a href="{% url 'polls:profile' user.username %}">Смотреть профиль пользователя {{ user.username }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет пользователей</p>
    {% endif %}
{% endblock %}

polls_backend/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

polls_backend/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
         {% include 'includes/checking_form_errors.html' %}

          <form method="post" action="{% url 'login' %}">
          {% csrf_token %}

          {% include 'includes/form_card.html' %}
          
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

polls_backend/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Регистрацияs{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% include 'includes/checking_form_errors.html' %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% include 'includes/form_card.html' %}
              
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %} 